<a href="https://colab.research.google.com/github/WoojinCho-Ryan/Studying-Pytorch/blob/main/3_Machine_Learning_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3-1. Linear Regression and Autograd

In [4]:
import torch

## 1. Data Definition

### 1) 훈련 데이터셋과 테스트 데이터셋
예측을 위해 사용하는 데이터: training dataset

model이 얼마나 잘 작동하는지 판별하는 데이터: test dataset

### 2) training dataset의 구성
model을 학습시키기 위한 데이터는 PyTorch의 torch.tensor를 가지고 있어야 함.

또한 input과 ouotput을 각기 다른 tensor에 저장해야 하며, 보편적으로 input: x, output: y.

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

## 2. Hypothesis 수립
ML에서 식을 세울 때, 이 식을 Hypothesis라고 함.

일반적으로 Linear regression의 hypothesis는 y = Wx + b 또는 H(x) = Wx + b로 표기함. 여기서 W: Weight, b: bias.

## 3. Cost function에 대한 이해
cost function = loss function = error function = objective function
$cost(W, b) = \frac{1}{n} \sum_{i=1}^{n} [y^{(i)} - H(x^{(i)})]^2$를 minimize하는 W와 b가 training dataset를 가장 잘 나타내는 직선을 표현


## 4. Gradient Descent
**Optimizer** Algorithm - Gradient Descent
$$W := W - \alpha \frac{\partial}{\partial W} cost(W)$$

## 5. Pytorch로 linear regression implement

### 1) 기본 셋팅

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [7]:
# 현재 실습하고 있는 python code를 재실행해도 다음에도 같은 결과가 나오도록 random seed 설정
torch.manual_seed(1)

### 2) 변수 선언

In [8]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [9]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [10]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


### 3) Weight와 bias의 초기화

In [11]:
# weight W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [12]:
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)


### 4) Hypothesis 세우기
H(x) = Wx + b

In [13]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 5) Cost function 선언하기

In [14]:
# 앞서 배운 torch.mean으로 평균을 구함.
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


### 6) Gradient Descent implement

In [15]:
# 'SGD'는 Gradient Descent의 일종. lr은 learning rate을 의미함.
optimizer = optim.SGD([W, b], lr = 0.01)

In [16]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# cost function을 derivative하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

7) 전체 코드

In [17]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000 # 원하는만큼 Gradient Descent을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

Epoch: 전체 training dataset이 학습에 한 번 사용된 period. (여기서는 2000번)

실제 정답은 W=2, b=0인 것을 보아 거의 정답을 찾은 셈.

##6. optimizer.zero_grad()가 필요한 이유
PyTorch는 derivative을 통해 얻은 slope을 이전에 계산된 slope 값에 누적시키는 특징이 있음.

In [19]:
import torch
w = torch.tensor(2.0, requires_grad = True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2 * w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


7. torch.manual_seed()를 하는 이유

In [20]:
import torch

In [21]:
torch.manual_seed(3)
print('random seed가 3일 때')
for i in range(1, 3):
  print(torch.rand(1))

random seed가 3일 때
tensor([0.0043])
tensor([0.1056])


In [22]:
torch.manual_seed(5)
print('random seed가 5일 때')
for i in range(1, 3):
  print(torch.rand(1))

random seed가 5일 때
tensor([0.8303])
tensor([0.1261])


In [23]:
torch.manual_seed(3)
print('random seed가 다시 3일 때')
for i in range(1, 3):
  print(torch.rand(1))

random seed가 다시 3일 때
tensor([0.0043])
tensor([0.1056])


## 8. Autograd 실습하기

임의로 2w^2 + 5라는 식을 세우고, w에 대해 미분해보자.

In [24]:
import torch

In [25]:
w = torch.tensor(2.0, requires_grad = True)

In [26]:
y = w ** 2
z = 2 * y + 5

In [27]:
z.backward()

In [28]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


-------------------------------------------------

#3-2. Multivariable Linear regression
앞서 배운 $x$가 1개인 linear regression을 Simple Linear Regression이라고 한다. 여기서는 다수의 $x$로부터 $y$를 예측하는 Multivariable Linear Regression에 대하여 이해한다.

## 1. Data Definition
| Quiz 1 (x1) | Quiz 2 (x2) | Quiz 3 (x3) | Final (y) |
| :---: | :---: | :---: | :---: |
| 73 | 80 | 75 | 152 |
| 93 | 88 | 93 | 185 |
| 89 | 91 | 80 | 180 |
| 96 | 98 | 100 | 196 |
| 73 | 66 | 70 | 142 |

다음과 같은 training dataset이 있다. 이번에는 독립 변수 $x$의 개수가 3개라는 점을 참고하여, final score를 예측하는 model을 만들어보자.

$H(x) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3} + b$

## 2. Pytorch로 구현하기

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [31]:
torch.manual_seed(1)

In [32]:
# training set
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [33]:
# weight w와 bias b 초기화
w1 = torch.zeros(1, requires_grad = True)
w2 = torch.zeros(1, requires_grad = True)
w3 = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

In [34]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr = 1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

  # H(x)
  hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

  # cost
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  # 100번마다 로그 출력
  if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))


Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


## 3. Vector와 Matrix 연산으로 바꾸기

### 1) Vector 연산으로 이해하기
$H(X) = w_{1}x_{1} + w_{2}x_{2} + w_{3}x_{3}$는 아래와 같이 두 vector의 dot product로 표현 가능하다.

$$\begin{pmatrix} x_1 & x_2 & x_3 \end{pmatrix} \cdot \begin{pmatrix} w_1 \\ w_2 \\ w_3 \end{pmatrix} = (x_1 w_1 + x_2 w_2 + x_3 w_3)$$

두 vector를 각각 $X$, $W$로 표현하면 $H(X) = XW$로 쓸 수 있다.

### 2) Matrix 연산으로 이해하기

$$
\begin{pmatrix}
x_{11} & x_{12} & x_{13} \\
x_{21} & x_{22} & x_{23} \\
x_{31} & x_{32} & x_{33} \\
x_{41} & x_{42} & x_{43} \\
x_{51} & x_{52} & x_{53}
\end{pmatrix}
\begin{pmatrix}
w_{1} \\
w_{2} \\
w_{3}
\end{pmatrix}
+
\begin{pmatrix}
b \\
b \\
b \\
b \\
b
\end{pmatrix}
=
\begin{pmatrix}
x_{11}w_{1} + x_{12}w_{2} + x_{13}w_{3} + b \\
x_{21}w_{1} + x_{22}w_{2} + x_{23}w_{3} + b \\
x_{31}w_{1} + x_{32}w_{2} + x_{33}w_{3} + b \\
x_{41}w_{1} + x_{42}w_{2} + x_{43}w_{3} + b \\
x_{51}w_{1} + x_{52}w_{2} + x_{53}w_{3} + b
\end{pmatrix}
$$



$H(X) = XW + B$

## 4. Matrix 연산을 고려하여 PyTorch로 구현하기

In [35]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 80],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [36]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [ ]:
# Weight와 bias 선언
W = torch.zeros((3, 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

여기서 주목할 점은 $W$의 크기가 (3 x 1) vector라는 점이다. 이는 matrix의 곱셈이 성립되기 위함이다.

In [37]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # bias b는 broadcasting되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

In [38]:
# 임의의 입력 값에 대한 에측
with torch.no_grad(): # 이 블록 안에서 수행되는 모든 연산에 대해 역전파(즉, slope 계산)을 비활성화함.
  new_input = torch.FloatTensor([[75, 85, 72]]) # 예측하고 싶은 임의의 입력
  prediction = new_input.matmul(W) + b
  print('Predicted value for input {}: {}'.format(new_input.squeeze().tolist(), prediction.item()))

Predicted value for input [75.0, 85.0, 72.0]: 156.8051300048828


# 3-3. nn.Module과 Class로 구현하기

이번에는 PyTorch에서 이미 구현되어져 제공되고 있는 함수들을 불러오는 것으로 더 쉽게 linear regression model을 구현할 예정.

예를 들면 PyTorch에서는 linear regression model이 nn.Linear()라는 함수로, 또 평균 제곱오차가 nn.functional.mse_loss()라는 함수로 구현되어 있음.

## 1. 단순 선형 회귀 구현하기

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [3]:
torch.manual_seed(1)

이제 데이터를 선언함. 아래 데이터는 y=2x를 가정된 상태에서 만들어진 데이터로 우리는 이미 정답이 W = 2, b = 0임을 알고 있는 사태. 모델이 이 두 W와 b의 값을 제대로 찾아내도록 하는 것이 목표.

In [4]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [5]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim = 1, output_dim = 1.
model = nn.Linear(1, 1)

model에는 weight W와 bias b가 저장되어져 있음. 이 값은 model.parameters()라는 함수를 사용하여 불러올 수 있음.

In [6]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [7]:
# optimizer 설정. Gradient Descent SGD를 사용하고 learning rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [8]:
# 전체 training dataset에 대해 Gradient Descent를 2000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs + 1):

  # H(x) 계산
  prediction = model(x_train)

  # cost 계산
  cost = F.mse_loss(prediction, y_train) # Pytorch에서 제공하는 평균 제곱 오차 함수

  # cost로 H(x) 개선하는 부분
  # gradient를 0으로 초기화
  optimizer.zero_grad()
  # cost function을 미분하여 gradient 계산
  cost.backward()
  # W와 b를 업데이트
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [9]:
# 임의의 입력 4를 선언
new_var = torch.FloatTensor([[4.0]])

pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [10]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


## 2. 다중 선형 회귀 구현하기

In [28]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [29]:
torch.manual_seed(1)

In [30]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [31]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim = 3, output_dim = 1.
model = nn.Linear(3, 1)

In [32]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [33]:
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [34]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [36]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [37]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


## 3. 모델을 클래스로 구현하기

In [38]:
class LinearRegressionModel(nn.Module): # torch.nn.Module을 상속받는 python class
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1, 1) # 단순 선형 회귀이므로 input_dim = 1, output_dim = 1.

  def forward(self, x):
    return self.linear(x)

In [39]:
model = LinearRegressionModel()

위와 같은 class를 사용한 model implement 형식은 대부분의 PyTorch 구현체에서 사용하고 있는 방식으로 반드시 숙지하고 있어야 함.

In [40]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [41]:
model = MultivariateLinearRegressionModel()

### 4. 단순 선형 회귀 클래스로 구현하기

In [42]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [43]:
torch.manual_seed(1)

In [44]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [45]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [46]:
model = LinearRegressionModel()

In [47]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [48]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


### 5. 다중 선형 회귀 클래스로 구현하기

In [49]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [50]:
torch.manual_seed(1)

In [51]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [52]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

model = MultivariateLinearRegressionModel()

In [53]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [54]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


# 3-4. Mini Batch and DataLoader

여기서 다루는 내용은 linear regression에 한정되는 내용은 아님. 여기서는 데이터를 로드하는 방법과 Minibatch Gradient Descent에 대해 다룸.

## 1. Mini Batch and Batch Size

In [55]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

만약 data의 개수가 매우 많다면 전체 데이터에 대해 gradient descent를 수행하는 것은 매우 느릴 뿐만 아니라 많은 계산량이 필요.

따라서 전체 data를 더 작은 단위로 나누어서 해당 단위로 학습하는 개념이 등장. 이 단위를 **Mini Batch**라고 함.

- Mini Batch 학습에서는 Mini Batch의 개수만큼 gradient descent를 수행해야 전체 data가 한 번 전부 사용되어 1 Epoch가 됨. 여기서 Mini Batch의 크기를 **batch size**라고 함.

- 전체 데이터에 대해서 한 번에 경사 하강법을 수행하는 방법을 '배치 경사 하강법'이라고 부름. 반면, 미니 배치 단위로 경사 하강법을 수행하는 방법을 '미니 배치 경사 하강법'이라고 부름.

- 배치 경사 하강법은 경사 하강법을 할 때, 전체 데이터를 사용하므로 가중치 값이 최적값에 수렴하는 과정이 매우 안정적이지만, 계산량이 너무 많이 필요. 미니 배치 경사 하강법은 경사 하강법을 할 때, 전체 데이터의 일부만을 보고 수행하므로 최적값으로 수렴하는 과정에서 값이 조금 헤매기도 하지만 훈련 속도가 빠름.

- 보통 batch size는 2의 제곱수를 사용. 그 이유는 CPU와 GPU의 메모리가 2의 배수이므로 데이터 송수신의 효율을 높일 수 있음.


## 2. Iteration

Total data = Iteration * Batch size

## 3. Data Load

In [56]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [57]:
from torch.utils.data import TensorDataset # TensorDataset
from torch.utils.data import DataLoader # DataLoader

In [58]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [59]:
dataset = TensorDataset(x_train, y_train)

Dataset을 생성했다면 DataLoader를 사용 가능. DataLoader는 기본적으로 2개의 argument를 입력받는다 (Dataset, Batch size). 추가적으로 shuffle이라는 argument가 많이 사용된다. shuffle = True를 선택하면 Epoch마다 dataset을 섞어서 data의 학습 순서를 바꿈.

In [60]:
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [62]:
model = nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [63]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 21981.667969
Epoch    0/20 Batch 2/3 Cost: 9587.075195
Epoch    0/20 Batch 3/3 Cost: 3180.415527
Epoch    1/20 Batch 1/3 Cost: 656.754761
Epoch    1/20 Batch 2/3 Cost: 208.265381
Epoch    1/20 Batch 3/3 Cost: 60.448395
Epoch    2/20 Batch 1/3 Cost: 20.464521
Epoch    2/20 Batch 2/3 Cost: 4.721592
Epoch    2/20 Batch 3/3 Cost: 7.182361
Epoch    3/20 Batch 1/3 Cost: 1.647293
Epoch    3/20 Batch 2/3 Cost: 0.378707
Epoch    3/20 Batch 3/3 Cost: 1.522778
Epoch    4/20 Batch 1/3 Cost: 1.254019
Epoch    4/20 Batch 2/3 Cost: 2.134122
Epoch    4/20 Batch 3/3 Cost: 0.052373
Epoch    5/20 Batch 1/3 Cost: 0.230407
Epoch    5/20 Batch 2/3 Cost: 1.461842
Epoch    5/20 Batch 3/3 Cost: 2.749334
Epoch    6/20 Batch 1/3 Cost: 1.041582
Epoch    6/20 Batch 2/3 Cost: 1.587178
Epoch    6/20 Batch 3/3 Cost: 1.168184
Epoch    7/20 Batch 1/3 Cost: 0.446067
Epoch    7/20 Batch 2/3 Cost: 2.133462
Epoch    7/20 Batch 3/3 Cost: 0.879393
Epoch    8/20 Batch 1/3 Cost: 0.129102
Epoch    

In [64]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.9222]], grad_fn=<AddmmBackward0>)


## 4. Custom Dataset

torch.utils.data.Dataset을 상속받아서 직접 Custom Dataset을 만드는 경우도 있음. torch.utils.data.Dataset은 PyTorch에서 dataset을 제공하는 추상 클래스.

가장 기본적인 뼈대는 아래와 같음.

In [ ]:
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self): # dataset의 전처리를 해주는 부분

  def __len__(self): # dataset의 길이. 즉, 총 sample의 수를 적어주는 부분

  def __getitem__(self, idx): # dataset에서 특정 1개의 sample을 가져오는 함수

## 5. Custom Dataset으로 linear regression 구현하기

In [67]:
import torch
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [69]:
# Dataset 상속
class CustomDataset(Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 data의 개수를 return
  def __len__(self):
    return len(self.x_data)

  # index를 입력받아 그에 맵핑되는 입출력 data를 PyTorch의 Tensor 형태로 return
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [70]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [71]:
model = torch.nn.Linear(3, 1)
optimizer = torch.optim.SGD(model.parameters(), lr = 1e-5)

In [72]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 29319.011719
Epoch    0/20 Batch 2/3 Cost: 7682.496094
Epoch    0/20 Batch 3/3 Cost: 3114.664795
Epoch    1/20 Batch 1/3 Cost: 809.167480
Epoch    1/20 Batch 2/3 Cost: 300.709198
Epoch    1/20 Batch 3/3 Cost: 37.518803
Epoch    2/20 Batch 1/3 Cost: 37.871727
Epoch    2/20 Batch 2/3 Cost: 3.583126
Epoch    2/20 Batch 3/3 Cost: 15.499701
Epoch    3/20 Batch 1/3 Cost: 3.772459
Epoch    3/20 Batch 2/3 Cost: 2.178463
Epoch    3/20 Batch 3/3 Cost: 0.037612
Epoch    4/20 Batch 1/3 Cost: 0.297060
Epoch    4/20 Batch 2/3 Cost: 2.369325
Epoch    4/20 Batch 3/3 Cost: 2.928143
Epoch    5/20 Batch 1/3 Cost: 1.220536
Epoch    5/20 Batch 2/3 Cost: 1.797108
Epoch    5/20 Batch 3/3 Cost: 1.805787
Epoch    6/20 Batch 1/3 Cost: 0.409901
Epoch    6/20 Batch 2/3 Cost: 2.198052
Epoch    6/20 Batch 3/3 Cost: 2.823555
Epoch    7/20 Batch 1/3 Cost: 1.618690
Epoch    7/20 Batch 2/3 Cost: 1.817694
Epoch    7/20 Batch 3/3 Cost: 2.327748
Epoch    8/20 Batch 1/3 Cost: 2.224417
Epoch   

In [73]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.6855]], grad_fn=<AddmmBackward0>)
