<a href="https://colab.research.google.com/github/WoojinCho-Ryan/Studying-Pytorch/blob/main/3_Machine_Learning_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3-1. Linear Regression and Autograd

In [4]:
import torch

## 1. Data Definition

### 1) 훈련 데이터셋과 테스트 데이터셋
예측을 위해 사용하는 데이터: training dataset

model이 얼마나 잘 작동하는지 판별하는 데이터: test dataset

### 2) training dataset의 구성
model을 학습시키기 위한 데이터는 PyTorch의 torch.tensor를 가지고 있어야 함.

또한 input과 ouotput을 각기 다른 tensor에 저장해야 하며, 보편적으로 input: x, output: y.

In [5]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

## 2. Hypothesis 수립
ML에서 식을 세울 때, 이 식을 Hypothesis라고 함.

일반적으로 Linear regression의 hypothesis는 y = Wx + b 또는 H(x) = Wx + b로 표기함. 여기서 W: Weight, b: bias.

## 3. Cost function에 대한 이해
cost function = loss function = error function = objective function
$cost(W, b) = \frac{1}{n} \sum_{i=1}^{n} [y^{(i)} - H(x^{(i)})]^2$를 minimize하는 W와 b가 training dataset를 가장 잘 나타내는 직선을 표현


## 4. Gradient Descent
**Optimizer** Algorithm - Gradient Descent
$$W := W - \alpha \frac{\partial}{\partial W} cost(W)$$

## 5. Pytorch로 linear regression implement

### 1) 기본 셋팅

In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [7]:
# 현재 실습하고 있는 python code를 재실행해도 다음에도 같은 결과가 나오도록 random seed 설정
torch.manual_seed(1)

### 2) 변수 선언

In [8]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [9]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [10]:
print(y_train)
print(y_train.shape)

tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


### 3) Weight와 bias의 초기화

In [11]:
# weight W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [12]:
b = torch.zeros(1, requires_grad = True)
print(b)

tensor([0.], requires_grad=True)


### 4) Hypothesis 세우기
H(x) = Wx + b

In [13]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


### 5) Cost function 선언하기

In [14]:
# 앞서 배운 torch.mean으로 평균을 구함.
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


### 6) Gradient Descent implement

In [15]:
# 'SGD'는 Gradient Descent의 일종. lr은 learning rate을 의미함.
optimizer = optim.SGD([W, b], lr = 0.01)

In [16]:
# gradient를 0으로 초기화
optimizer.zero_grad()
# cost function을 derivative하여 gradient 계산
cost.backward()
# W와 b를 업데이트
optimizer.step()

7) 전체 코드

In [17]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 2000 # 원하는만큼 Gradient Descent을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/2000 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/2000 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/2000 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/2000 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/2000 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/2000 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/2000 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/2000 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/2000 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/2000 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/2000 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/2000 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/2000 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/2000 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/2000 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/2000 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/2000 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/2000 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/2000 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/2000 W: 1.997, b: 0.008 Cost: 0.000008

Epoch: 전체 training dataset이 학습에 한 번 사용된 period. (여기서는 2000번)

실제 정답은 W=2, b=0인 것을 보아 거의 정답을 찾은 셈.

##6. optimizer.zero_grad()가 필요한 이유
PyTorch는 derivative을 통해 얻은 slope을 이전에 계산된 slope 값에 누적시키는 특징이 있음.

In [19]:
import torch
w = torch.tensor(2.0, requires_grad = True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2 * w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


7. torch.manual_seed()를 하는 이유

In [20]:
import torch

In [21]:
torch.manual_seed(3)
print('random seed가 3일 때')
for i in range(1, 3):
  print(torch.rand(1))

random seed가 3일 때
tensor([0.0043])
tensor([0.1056])


In [22]:
torch.manual_seed(5)
print('random seed가 5일 때')
for i in range(1, 3):
  print(torch.rand(1))

random seed가 5일 때
tensor([0.8303])
tensor([0.1261])


In [23]:
torch.manual_seed(3)
print('random seed가 다시 3일 때')
for i in range(1, 3):
  print(torch.rand(1))

random seed가 다시 3일 때
tensor([0.0043])
tensor([0.1056])


## 8. Autograd 실습하기

임의로 2w^2 + 5라는 식을 세우고, w에 대해 미분해보자.

In [24]:
import torch

In [25]:
w = torch.tensor(2.0, requires_grad = True)

In [26]:
y = w ** 2
z = 2 * y + 5

In [27]:
z.backward()

In [28]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0
